### ISSUE TITLE
SSH interactive tunneling input appears duplicate when I redirect Input & outputstream to other than System.in & System.out

### ISSUE THREAD

**Issue by ThanasisBarekas** [Nordstrom/Remote-Session#11]
Hello,

Thank you for this great library. I am raising this issue because I need your support.
I am trying to get remote interactive session to another machine when user gives a specific ShellMethod (Using https://github.com/fonimus/ssh-shell-spring-boot library)  that simulates a cli command.
I need to provide the InputStream and the OutputStream from SSH-Spring-shell library to the Remote-Session library. Everything works well but upon typing all characters appear 2 times but are send to remote 1 time as they should be.

Here is the simple code I using to implement this :

@ShellMethod("CM_with_nordstrom")
public String ssh_to_cm() throws IOException {

    InputStream is = ((SshContext) SshShellCommandFactory.SSH_THREAD_CONTEXT.get()).getTerminal().input();//System.in;
    OutputStream os = ((SshContext) SshShellCommandFactory.SSH_THREAD_CONTEXT.get()).getTerminal().output();//System.out;
    SshUtils.shell("ssh://root:pswd@ip", is, os);
    return "Ssh tunnel to CM ended";
}
Also in order to get autocomplete functionality from the interactive session I need to press tab twice. Any Clue why these duplications happen?

Thank you,
Thanasis

**Comment by sbabcoc** [comment]
Unfortunately, I've never tried the implement this sort of scenario. I suspect that what you're seeing is caused by logging of both input stream and output stream, but have not tested this theory. By the way, if that IP address in your initial post corresponds to an actual system, you should probably replace it with a placeholder.

**Comment by ThanasisBarekas** [comment]
Thank you very much for your response, you are correct. One character appears due to typing from the inpustream and one appears because it is also typed to the remote shell and brought back to local shell.
Is there any plan for testing this or providing some handling ? 
Changed also the ip :)

Thank you,
Thanasis

**Comment by sbabcoc** [comment]
As far as I know, Remote-Session isn't logging the content you're seeing, so I'm not sure how I'd fix this issue.
